# ReplicaSet API 버전: apps/v1
# ReplicaSet 이름: myapp-replicaset
# ReplicaSet replicas: 3

# 컨테이너 이름/포트: my-app(8080)
# 컨테이너 레이블: app=my-app
# 도커 이미지: yoonjeong/my-app:2.0-unhealthy
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
      - name: my-app
        image: yoonjeong/my-app:2.0-unhealthy
        ports:
        - containerPort: 8080
        resources:
          limits: 
            memory: "64Mi"
            cpu: "50m"