# Pod API 버전: v1
# Pod 이름: sky-app-1
# 레이블: group=nature
# 컨테이너 이름/포트: sky-app(8080)
# 도커 이미지: yoonjeong/blue-app:1.0
apiVersion: v1
kind: Pod
metadata:
  name: sky-app-1
  labels:
    group: nature
spec:
  containers:
  - name: sky-app
    image: yoonjeong/blue-app:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
